### ISSUE TITLE
Are thera  about any  features of priority  ? 

### ISSUE THREAD

**Issue by opticaloptical** [manfred-kaiser/business-rule-engine#13]
I couldn't find it in document,thanks

**Comment by manfred-kaiser** [comment]
What do you mean with 'features of priority'?

Do you mean 'execution order'? The rules are evaluated in the defined order. 

If you need to evaluate rules in a different order, you have to implement this in you program. I think, this is not a requirement for the rule engine, because you can order the rules, when reading from a database or something similar.
