### ISSUE TITLE
Adding String values  in params as conditions

### ISSUE THREAD

**Issue by Ashish-Soni08** [manfred-kaiser/business-rule-engine#17]
```
params = {
      'item_name': 'Mango'
}

items = ['apple', 'Mango', 'Bread', 'Grapes', 'Fish']


def [check_exists(list_items):
  if product_name in list_items:
    list_items.remove(item_name)
  return list_items

rules = """
rule "remove items"
when 
    item_name
then 
    check_exists(items)
end
"""

from business_rule_engine import RuleParser
parser = RuleParser()
parser.register_function(check_exists)
parser.parsestr(rules)
parser.execute(params) --- error 

````
Can you please guide me here, in terms of how can I implement my idea using this library?? 
and if I have to check for more than one item existing in a list, should I list all of the items one by one in params??  
and create an individual rule for each of the items in rules?? 

![br_error](https://user-images.githubusercontent.com/44482363/151683725-13984e47-942a-4039-b6f3-51414d5c6413.PNG)

**Comment by manfred-kaiser** [comment]
I would recommend not modifying your parameters with business rules during rule evaluation. 

While this is possible with custom functions, the problem is, that other rules, which depend on modified parameters could return different results. It's should be possible to execute rules in different order and all rules should be deterministic. This means, if you provide the same input to the rule parser the rules should always return the same results.

But it's up to you and your application if this is a strict requirement or not.

Your rules have some problems. The rule parser requires Excel like formulas for the condition and for the action. Your condition is only valid for python but not as Excel formula. The next problem is, that "items" was not passed as parameter to the rule parser.

If you want to check if a specific item exists, you can use `COUNTIF` example: `COUNTIF(items, item_to_remove) > 0`-
COUNTIF only supports 1 item and loops are not possible.

At the moment, `COUNTIFS`, which allows to check a list against another list is not implemented, but you can create a custom function for that:

Example, whcih checks if one or more items are in the list. If the condition is true, items will be removed from the list.

```python
from business_rule_engine import RuleParser
import formulas


def remove_if_exists(list_items, items_to_check):
    list_items[:] = [item for item in list_items if item not in items_to_check]


def COUNTIFS(range1, criteria1):
    count = 0
    for crit in criteria1:
        count += formulas.get_functions()['COUNTIF'](range1, crit)
    return count


items = ['apple', 'Mango', 'Bread', 'Grapes', 'Fish']
params = {
    'items_to_remove': ["Mango", "apple"],
    'items': items
}


rules = """
rule "remove items"
when 
    COUNTIFS(items, items_to_remove) > 0
then 
    remove_if_exists(items, items_to_remove)
end
"""

parser = RuleParser(condition_requires_bool=False)
parser.register_function(remove_if_exists)
parser.register_function(COUNTIFS)
parser.parsestr(rules)
parser.execute(params)
print(items)
```

I hope this will help you with your project.

**Comment by Ashish-Soni08** [comment]
Thank you very much for the guidance @manfred-kaiser :)
